export const jobPostings = [
  {
    id: 1,
    jobTitle: "Software Engineer",
    company: "Tech Corp",
    location: "San Francisco, CA",
    description:
      "We are looking for a skilled Software Engineer to develop and maintain our web applications. The ideal candidate has experience with JavaScript, React, and Node.js.",
    salary: "$120,000 - $140,000",
    level: "Mid-Level",
    type: "Full-Time",
    postedDate: "2023-10-01",
    skillsRequired: ["JavaScript", "React", "Node.js", "HTML", "CSS"],
  },
  {
    id: 2,
    jobTitle: "Data Scientist",
    company: "Data Insights Inc.",
    location: "New York, NY",
    description:
      "Join our team as a Data Scientist to analyze large datasets and build predictive models. Proficiency in Python, R, and machine learning is required.",
    salary: "$130,000 - $150,000",
    level: "Senior",
    type: "Full-Time",
    postedDate: "2023-10-05",
    skillsRequired: ["Python", "R", "Machine Learning", "Data Analysis", "SQL"],
  },
  {
    id: 3,
    jobTitle: "Product Manager",
    company: "Innovate Tech",
    location: "Austin, TX",
    description:
      "We are seeking a Product Manager to lead the development of our new product line. The ideal candidate has experience in Agile methodologies and a strong technical background.",
    salary: "$110,000 - $130,000",
    level: "Mid-Level",
    type: "Full-Time",
    postedDate: "2023-10-10",
    skillsRequired: [
      "Product Management",
      "Agile",
      "Scrum",
      "JIRA",
      "Market Research",
    ],
  },
  {
    id: 4,
    jobTitle: "UX/UI Designer",
    company: "Creative Solutions",
    location: "Seattle, WA",
    description:
      "We are looking for a talented UX/UI Designer to create intuitive and visually appealing user interfaces. Experience with Figma, Sketch, and Adobe XD is a must.",
    salary: "$90,000 - $110,000",
    level: "Junior",
    type: "Full-Time",
    postedDate: "2023-10-15",
    skillsRequired: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "User Research",
      "Wireframing",
    ],
  },
  {
    id: 5,
    jobTitle: "DevOps Engineer",
    company: "Cloud Innovators",
    location: "Remote",
    description:
      "We are hiring a DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines. Experience with AWS, Docker, and Kubernetes is required.",
    salary: "$140,000 - $160,000",
    level: "Senior",
    type: "Full-Time",
    postedDate: "2023-10-20",
    skillsRequired: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
  },
  {
    id: 6,
    jobTitle: "Marketing Specialist",
    company: "Global Marketing Co.",
    location: "Chicago, IL",
    description:
      "We are looking for a Marketing Specialist to develop and execute marketing campaigns. Experience with digital marketing, SEO, and social media is preferred.",
    salary: "$70,000 - $90,000",
    level: "Junior",
    type: "Full-Time",
    postedDate: "2023-10-25",
    skillsRequired: [
      "Digital Marketing",
      "SEO",
      "Social Media",
      "Content Creation",
      "Analytics",
    ],
  },
];
